PRAGMA foreign_keys = OFF;
PRAGMA defer_foreign_keys = true;

DROP TABLE IF EXISTS `streetGeometry`;
DROP TABLE IF EXISTS `divisionStatistics`;
DROP TABLE IF EXISTS `statsRecords`;
DROP TABLE IF EXISTS `statsObservationDimensions`;
DROP TABLE IF EXISTS `statsValuesI18n`;
DROP TABLE IF EXISTS `statsFieldsI18n`;
DROP TABLE IF EXISTS `statsFields`;
DROP TABLE IF EXISTS `snapshotVersionChanges`;
DROP TABLE IF EXISTS `streetChangelog`;
DROP TABLE IF EXISTS `streetNameChangeStreets`;
DROP TABLE IF EXISTS `streetNameChanges`;
DROP TABLE IF EXISTS `placesI18n`;
DROP TABLE IF EXISTS `places`;
DROP TABLE IF EXISTS `streetsI18n`;
DROP TABLE IF EXISTS `streets`;
DROP TABLE IF EXISTS `address3dUnitRefLookup`;
DROP TABLE IF EXISTS `address3dI18n`;
DROP TABLE IF EXISTS `address3d`;
DROP TABLE IF EXISTS `address2dBuildingNumberLookup`;
DROP TABLE IF EXISTS `address2dI18n`;
DROP TABLE IF EXISTS `address2d`;
DROP TABLE IF EXISTS `divisionsI18n`;
DROP TABLE IF EXISTS `divisions`;
DROP TABLE IF EXISTS `divisionBoundaries`;
DROP TABLE IF EXISTS `divisionAreas`;
DROP TABLE IF EXISTS `d1_migrations`;

PRAGMA foreign_keys = ON;
