PRAGMA foreign_keys = OFF;
PRAGMA defer_foreign_keys = true;

DROP TABLE IF EXISTS `hkgovPlandNewTownDivisionAreaI18n`;
DROP TABLE IF EXISTS `hkgovPlandNewTownDivisionAreas`;
DROP TABLE IF EXISTS `hkgovPlandDivisionI18n`;
DROP TABLE IF EXISTS `hkgovPlandDivisionAreas`;
DROP TABLE IF EXISTS `hkgovPlandDivisions`;
DROP TABLE IF EXISTS `hkgovPlandPlanningCells`;
DROP TABLE IF EXISTS `hkgovAlsAddress2dI18n`;
DROP TABLE IF EXISTS `hkgovAlsAddresses2d`;
DROP TABLE IF EXISTS `hkgovHadDivisionAreas`;
DROP TABLE IF EXISTS `hkgovCenstatdDivisionAreaI18n`;
DROP TABLE IF EXISTS `hkgovCenstatdDivisionAreaDerivatives`;
DROP TABLE IF EXISTS `hkgovCenstatdDivisionAreas`;
DROP TABLE IF EXISTS `hkgovLandsdStreetNoticeI18n`;
DROP TABLE IF EXISTS `hkgovLandsdStreetNoticeApplications`;
DROP TABLE IF EXISTS `hkgovLandsdStreetNotices`;
DROP TABLE IF EXISTS `hkgovLandsdStreetBaselineRecordI18n`;
DROP TABLE IF EXISTS `hkgovLandsdStreetBaselineRecords`;
DROP TABLE IF EXISTS `hkgovLandsdStreetI18n`;
DROP TABLE IF EXISTS `hkgovLandsdStreets`;
DROP TABLE IF EXISTS `hkgovLandsdRoadCentrelineI18n`;
DROP TABLE IF EXISTS `hkgovLandsdRoadCentrelines`;
DROP TABLE IF EXISTS `overtureDivisionBoundaries`;
DROP TABLE IF EXISTS `overtureDivisionAreas`;
DROP TABLE IF EXISTS `overtureDivisionI18n`;
DROP TABLE IF EXISTS `overtureDivisions`;
DROP TABLE IF EXISTS `overturePlaceI18n`;
DROP TABLE IF EXISTS `overturePlaces`;
DROP TABLE IF EXISTS `stagingAddresses2d`;
DROP TABLE IF EXISTS `stagingAddresses2dI18n`;
DROP TABLE IF EXISTS `stagingAddresses2dChanged`;
DROP TABLE IF EXISTS `d1_migrations`;

PRAGMA foreign_keys = ON;
