PRAGMA foreign_keys = OFF;
PRAGMA defer_foreign_keys = true;

DROP TABLE IF EXISTS `streetGeometry`;
DROP TABLE IF EXISTS `divisionStatistics`;
DROP TABLE IF EXISTS `statsSeriesDimensions`;
DROP TABLE IF EXISTS `statsSeries`;
DROP TABLE IF EXISTS `statsObservationDimensions`;
DROP TABLE IF EXISTS `statsValuesI18n`;
DROP TABLE IF EXISTS `statsValues`;
DROP TABLE IF EXISTS `statsDimensions`;
DROP TABLE IF EXISTS `statsMeasuresI18n`;
DROP TABLE IF EXISTS `statsMeasures`;
DROP TABLE IF EXISTS `statsObservations`;
DROP TABLE IF EXISTS `placesFts`;
DROP TABLE IF EXISTS `placesFts_data`;
DROP TABLE IF EXISTS `placesFts_idx`;
DROP TABLE IF EXISTS `placesFts_content`;
DROP TABLE IF EXISTS `placesFts_docsize`;
DROP TABLE IF EXISTS `placesFts_config`;
DROP TABLE IF EXISTS `placesI18n`;
DROP TABLE IF EXISTS `placesDivision`;
DROP TABLE IF EXISTS `placesCells`;
DROP TABLE IF EXISTS `places`;
DROP TABLE IF EXISTS `__new_streetChangelog`;
DROP TABLE IF EXISTS `streetChangelog`;
DROP TABLE IF EXISTS `streetNameChangeStreets`;
DROP TABLE IF EXISTS `streetNameChanges`;
DROP TABLE IF EXISTS `__streetsI18n_backup`;
DROP TABLE IF EXISTS `__streetsAddress_backup`;
DROP TABLE IF EXISTS `__new_streets`;
DROP TABLE IF EXISTS `streetsAddress`;
DROP TABLE IF EXISTS `streetsI18n`;
DROP TABLE IF EXISTS `streets`;
DROP TABLE IF EXISTS `address3dUnitRefLookup`;
DROP TABLE IF EXISTS `address3dI18n`;
DROP TABLE IF EXISTS `address3d`;
DROP TABLE IF EXISTS `address2dBuildingNumberLookup`;
DROP TABLE IF EXISTS `address2dI18n`;
DROP TABLE IF EXISTS `address2d`;
DROP TABLE IF EXISTS `divisionsI18n`;
DROP TABLE IF EXISTS `divisions`;
DROP TABLE IF EXISTS `divisionBoundaries`;
DROP TABLE IF EXISTS `divisionAreas`;
DROP TABLE IF EXISTS `d1_migrations`;

PRAGMA foreign_keys = ON;
