PRAGMA foreign_keys = OFF;
PRAGMA defer_foreign_keys = true;

DROP TABLE IF EXISTS `apiFieldProvenance`;
DROP TABLE IF EXISTS `apiEndpointDatasets`;
DROP TABLE IF EXISTS `apiReleaseSetSnapshots`;
DROP TABLE IF EXISTS `apiReleaseSetSources`;
DROP TABLE IF EXISTS `apiCatalogRevisionReleaseSets`;
DROP TABLE IF EXISTS `apiCompositionMembers`;
DROP TABLE IF EXISTS `apiComposition`;
DROP TABLE IF EXISTS `snapshotAssemblySources`;
DROP TABLE IF EXISTS `snapshotAssemblyRuns`;
DROP TABLE IF EXISTS `snapshotAssembly`;
DROP TABLE IF EXISTS `releaseSetShardAssignments`;
DROP TABLE IF EXISTS `releaseShardAssignments`;
DROP TABLE IF EXISTS `snapshotShardAssignments`;
DROP TABLE IF EXISTS `snapshotSources`;
DROP TABLE IF EXISTS `ingestRuns`;
DROP TABLE IF EXISTS `stats`;
DROP TABLE IF EXISTS `historyVersionProvenance`;
DROP TABLE IF EXISTS `assets`;
DROP TABLE IF EXISTS `apiEndpoints`;
DROP TABLE IF EXISTS `apiReleaseSets`;
DROP TABLE IF EXISTS `dataShards`;
DROP TABLE IF EXISTS `snapshots`;
DROP TABLE IF EXISTS `snapshotLineages`;
DROP TABLE IF EXISTS `apiCatalogRevisions`;
DROP TABLE IF EXISTS `apiVersions`;
DROP TABLE IF EXISTS `entityAliases`;
DROP TABLE IF EXISTS `releaseProcessingActions`;
DROP TABLE IF EXISTS `releases`;
DROP TABLE IF EXISTS `datasetTransforms`;
DROP TABLE IF EXISTS `datasetI18n`;
DROP TABLE IF EXISTS `datasetResourceTypes`;
DROP TABLE IF EXISTS `datasets`;
DROP TABLE IF EXISTS `licenses`;
DROP TABLE IF EXISTS `publisherI18n`;
DROP TABLE IF EXISTS `publishedDataJournal`;
DROP TABLE IF EXISTS `publishers`;
DROP TABLE IF EXISTS `identifierBridges`;
DROP TABLE IF EXISTS `divisionIdentifierBridges`;
DROP TABLE IF EXISTS `api_key_usage`;
DROP TABLE IF EXISTS `api_key`;
DROP TABLE IF EXISTS `newsletterSubscription`;
DROP TABLE IF EXISTS `facebookDeletionRequest`;
DROP TABLE IF EXISTS `passkey`;
DROP TABLE IF EXISTS `verification`;
DROP TABLE IF EXISTS `account`;
DROP TABLE IF EXISTS `session`;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `d1_migrations`;

PRAGMA foreign_keys = ON;
