PRAGMA foreign_keys = OFF;
PRAGMA defer_foreign_keys = true;

DROP TABLE IF EXISTS `hkgovPlandNewTownDivisionAreas`;
DROP TABLE IF EXISTS `hkgovPlandDivisionAreas`;
DROP TABLE IF EXISTS `hkgovPlandDivisions`;
DROP TABLE IF EXISTS `hkgovPlandPlanningCells`;
DROP TABLE IF EXISTS `hkgovAlsAddresses2d`;
DROP TABLE IF EXISTS `hkgovTdPedestrianStreets`;
DROP TABLE IF EXISTS `hkgovHydStrategicStreets`;
DROP TABLE IF EXISTS `hkgovHydSensitiveStreets`;
DROP TABLE IF EXISTS `hkgovHydStreetNamePlates`;
DROP TABLE IF EXISTS `hkgovHadDivisionAreas`;
DROP TABLE IF EXISTS `hkgovCenstatdStatistics`;
DROP TABLE IF EXISTS `hkgovCenstatdDistrictLandAreaPopulationDensities`;
DROP TABLE IF EXISTS `hkgovCenstatdDivisionAreaDerivatives`;
DROP TABLE IF EXISTS `hkgovCenstatdDivisionAreas`;
DROP TABLE IF EXISTS `hkgovLandsdStreetNoticeApplications`;
DROP TABLE IF EXISTS `hkgovLandsdStreetNotices`;
DROP TABLE IF EXISTS `hkgovLandsdStreetBaselineRecords`;
DROP TABLE IF EXISTS `hkgovLandsdStreets`;
DROP TABLE IF EXISTS `hkgovLandsdRoadCentrelines`;
DROP TABLE IF EXISTS `hkgovLandsdPlaceNames`;
DROP TABLE IF EXISTS `overtureDivisionBoundaries`;
DROP TABLE IF EXISTS `overtureDivisionAreas`;
DROP TABLE IF EXISTS `overtureDivisions`;
DROP TABLE IF EXISTS `overturePlaces`;
DROP TABLE IF EXISTS `stagingAddresses2d`;
DROP TABLE IF EXISTS `stagingAddresses2dChanged`;
DROP TABLE IF EXISTS `d1_migrations`;

PRAGMA foreign_keys = ON;
