PRAGMA defer_foreign_keys = true;

DROP TABLE IF EXISTS `placesFts`;
DROP TABLE IF EXISTS `placesFts_data`;
DROP TABLE IF EXISTS `placesFts_idx`;
DROP TABLE IF EXISTS `placesFts_content`;
DROP TABLE IF EXISTS `placesFts_docsize`;
DROP TABLE IF EXISTS `placesFts_config`;
DROP TABLE IF EXISTS `placesI18n`;
DROP TABLE IF EXISTS `placesDivision`;
DROP TABLE IF EXISTS `placesCells`;
DROP TABLE IF EXISTS `places`;
DROP TABLE IF EXISTS `streetsAddress`;
DROP TABLE IF EXISTS `streetsI18n`;
DROP TABLE IF EXISTS `streets`;
DROP TABLE IF EXISTS `address3dI18n`;
DROP TABLE IF EXISTS `address3d`;
DROP TABLE IF EXISTS `address2dI18n`;
DROP TABLE IF EXISTS `address2d`;
DROP TABLE IF EXISTS `divisionsI18n`;
DROP TABLE IF EXISTS `divisions`;
DROP TABLE IF EXISTS `d1_migrations`;
