export type CreateAMapRenderer = 'maplibre' | 'mapbox' | 'leaflet'

export type CreateAMapRendererReference = {
  authCode: string
  code: string
  installCommand: string
  label: string
  setupInstruction?: string
  stylesheetCode: string
}

const stylesheetCode = [
  'html,',
  'body,',
  '#app,',
  '#map {',
  '  width: 100%;',
  '  height: 100%;',
  '  margin: 0;',
  '}',
].join('\n')

const authCode = [
  "type Audience = 'atlas-api' | 'basemap-tiles'",
  '',
  'type AccessToken = {',
  '  value: string',
  '  expiresAt: number',
  '}',
  '',
  'const key = import.meta.env.VITE_SAANSEOI_API_KEY',
  "if (!key?.startsWith('pk.')) {",
  "  throw new Error('Set VITE_SAANSEOI_API_KEY to your SaanSeoi public key.')",
  '}',
  '',
  'const tokens = new Map<Audience, AccessToken>()',
  'const refreshTimers = new Map<Audience, number>()',
  'const refreshMarginMs = 60_000',
  '',
  'async function refresh(audience: Audience) {',
  "  const response = await fetch('https://api.saanseoi.hk/v0/auth/tokens', {",
  "    method: 'POST',",
  "    headers: { 'content-type': 'application/json', 'x-api-key': key },",
  '    body: JSON.stringify({ audience }),',
  '  })',
  '',
  "  if (!response.ok) throw new Error('SaanSeoi could not refresh the access token.')",
  '  const { accessToken, expiresIn } = await response.json() as {',
  '    accessToken: string',
  '    expiresIn: number',
  '  }',
  '  const token = { value: accessToken, expiresAt: Date.now() + expiresIn * 1_000 }',
  '  tokens.set(audience, token)',
  '',
  '  const previousTimer = refreshTimers.get(audience)',
  '  if (previousTimer) window.clearTimeout(previousTimer)',
  '  refreshTimers.set(',
  '    audience,',
  '    window.setTimeout(() => void refresh(audience), Math.max(0, expiresIn * 1_000 - refreshMarginMs)),',
  '  )',
  '  return token',
  '}',
  '',
  'async function ready(audience: Audience) {',
  '  const token = tokens.get(audience)',
  '  return token && token.expiresAt - Date.now() > refreshMarginMs',
  '    ? token',
  '    : refresh(audience)',
  '}',
  '',
  'function headers(audience: Audience) {',
  '  const token = tokens.get(audience)',
  "  if (!token || token.expiresAt <= Date.now()) throw new Error('SaanSeoi access token is unavailable.')",
  '  return { Authorization: `Bearer ${token.value}` }',
  '}',
  '',
  'async function fetchApi(input: RequestInfo | URL, init?: RequestInit) {',
  "  await ready('atlas-api')",
  '  const requestHeaders = new Headers(init?.headers)',
  "  requestHeaders.set('Authorization', headers('atlas-api').Authorization)",
  '  return fetch(input, {',
  '    ...init,',
  '    headers: requestHeaders,',
  '  })',
  '}',
  '',
  'export const saanseoiAuth = { ready, headers, fetchApi }',
].join('\n')

const references: Record<CreateAMapRenderer, CreateAMapRendererReference> = {
  maplibre: {
    authCode,
    label: 'MapLibre',
    installCommand: 'bun add maplibre-gl',
    code: [
      "import { Map } from 'maplibre-gl'",
      "import 'maplibre-gl/dist/maplibre-gl.css'",
      "import './style.css'",
      '',
      "document.querySelector<HTMLDivElement>('#app')!.innerHTML = '<div id=\"map\"></div>'",
      '',
      'new Map({',
      "  container: 'map',",
      '  center: [114.1694, 22.3193],',
      '  zoom: 11,',
      '  style: {',
      '    version: 8,',
      '    sources: {},',
      '    layers: [',
      '      {',
      "        id: 'background',",
      "        type: 'background',",
      "        paint: { 'background-color': '#fff9ed' },",
      '      },',
      '    ],',
      '  },',
      '})',
    ].join('\n'),
    stylesheetCode,
  },
  mapbox: {
    authCode,
    label: 'Mapbox GL JS',
    installCommand: 'bun add mapbox-gl',
    setupInstruction:
      'Use the Mapbox access token already stored in local `.env` as `VITE_MAPBOX_TOKEN`. Do not ask for or reveal its value.',
    code: [
      "import mapboxgl from 'mapbox-gl'",
      "import 'mapbox-gl/dist/mapbox-gl.css'",
      "import './style.css'",
      '',
      "document.querySelector<HTMLDivElement>('#app')!.innerHTML = '<div id=\"map\"></div>'",
      '',
      'mapboxgl.accessToken = import.meta.env.VITE_MAPBOX_TOKEN',
      "// Mapbox Standard is Mapbox's hosted, ready-to-use basemap style.",
      'const map = new mapboxgl.Map({',
      "  container: 'map',",
      "  style: 'mapbox://styles/mapbox/standard',",
      '  center: [114.1694, 22.3193],',
      '  zoom: 11,',
      '})',
    ].join('\n'),
    stylesheetCode,
  },
  leaflet: {
    authCode,
    label: 'Leaflet',
    installCommand: 'bun add leaflet maplibre-gl maplibre-gl-leaflet',
    code: [
      "import L from 'leaflet'",
      "import 'leaflet/dist/leaflet.css'",
      "import './style.css'",
      '',
      "document.querySelector<HTMLDivElement>('#app')!.innerHTML = '<div id=\"map\"></div>'",
      '',
      "const map = L.map('map').setView([22.3193, 114.1694], 11)",
      "L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {",
      "  attribution: '© OpenStreetMap contributors',",
      '}).addTo(map)',
    ].join('\n'),
    stylesheetCode,
  },
}

export const isCreateAMapRenderer = (value?: string): value is CreateAMapRenderer =>
  value === 'maplibre' || value === 'mapbox' || value === 'leaflet'

export const getCreateAMapRendererReference = (renderer: CreateAMapRenderer) =>
  references[renderer]

export const createAMapRendererReferenceInstructions = (
  renderer: CreateAMapRenderer,
  headingLevel = 3,
) => {
  const reference = getCreateAMapRendererReference(renderer)
  const heading = '#'.repeat(headingLevel)

  return [
    `${heading} Setup`,
    '',
    `Install the latest version of ${reference.label} with:`,
    '',
    '```bash',
    reference.installCommand,
    '```',
    ...(reference.setupInstruction ? ['', reference.setupInstruction] : []),
    '',
    `${heading} Code edits`,
    '',
    'Replace the existing `src/main.ts` with:',
    '',
    '```ts',
    reference.code,
    '```',
    '',
    'Create `src/auth.ts` with:',
    '',
    '```ts',
    reference.authCode,
    '```',
    '',
    'Set `VITE_SAANSEOI_API_KEY` in your local `.env` file. This is a public key: it is embedded in the browser build and can be limited by origin from your SaanSeoi account.',
    '',
    'Replace the existing styles in `src/style.css` with:',
    '',
    '```css',
    reference.stylesheetCode,
    '```',
  ].join('\n')
}
