/**
 * Produces the DOM ID shared by the Markdown outline and rendered headings.
 * The slug itself is generated by the Markdown parser / GithubSlugger.
 */
export function getMarkdownHeadingId(slug: string) {
  return `source-heading-${slug}`
}
