name: 'TEST :: Run Tests'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  test:
    name: 'TEST :: ${{ matrix.app.name }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
          - name: 'Atlas API'
            path: 'apps/atlas-api'
            cache_key: 'atlas-api'
          - name: 'Harbour API'
            path: 'apps/harbour'
            cache_key: 'harbour'
    steps:
      - name: 'GIT :: Checkout'
        uses: actions/checkout@v4

      - name: 'INSTALL :: Bun'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.3.14'

      - name: 'CACHE :: Restore Dependencies'
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/bun.lock') }}

      - name: 'INSTALL :: Dependencies'
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: bun install --frozen-lockfile

      - name: 'CACHE :: Restore Build'
        uses: actions/cache@v3
        with:
          path: |
            .turbo
            ${{ matrix.app.path }}/dist
          key: ${{ runner.os }}-${{ matrix.app.cache_key }}-build-${{ inputs.environment }}-${{ hashFiles('bun.lock', 'turbo.json', 'package.json', 'apps/**', 'libs/**') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.app.cache_key }}-build-${{ inputs.environment }}-
            ${{ runner.os }}-${{ matrix.app.cache_key }}-build-

      - name: 'CHECK :: Types'
        run: bun run check
        working-directory: ${{ matrix.app.path }}

      - name: 'TEST :: Run tests'
        run: bun run test
        working-directory: ${{ matrix.app.path }}
